const DEFAULT_LOCALE = "en-US";

const translations = {
  en: {
    common_loading: "Loading...",
    common_close: "Close",
    common_save: "Save",
    common_cancel: "Cancel",
    common_confirm: "Confirm",
    common_reset: "Reset",
    common_remove: "Remove",
    common_delete: "Delete",
    common_link_work_item: "Link work item",
    common_link_existing_work_item: "Link existing work item",
    common_remove_link_to_work_item: "Remove link to work item",
    common_add_work_item_menu: "Add work item menu",
    common_add_work_item: "Add work item",
    common_copy_to_clipboard: "Copy to clipboard",
    common_download_pdf: "Download PDF",
    common_description: "Description",
    common_data: "Data",
    common_help: "Help",
    common_settings: "Settings",
    scroll_by_column: "Scroll by column",
    scroll_by_board: "Scroll by board",
    show_all_teams: "Show all teams",
    show_my_teams: "Show my teams",
    column_notes: "Column notes",
    edit_column_notes: "Edit column notes",
    add_new_feedback: "Add new feedback",
    remove_feedback_from_group: "Remove feedback from group",
    volunteer: "Volunteer",
    the_prime_directive: "The Prime Directive",
    open_retrospective_wiki: "Open retrospective wiki",
    open_user_guide: "Open user guide",
    open_contributing_guidelines: "Open contributing guidelines",
    prime_directive: "Directive",
    data_import_export: "Data Import/Export",
    import_data: "Import data",
    export_data: "Export data",
    retrospective_help: "Retrospective Help",
    retrospective_settings: "User/Admin Settings",
    whats_new: "What's new",
    keyboard_shortcuts: "Keyboard shortcuts",
    contact_us: "Contact us",
    user_guide: "User guide",
    prime_directive_purpose: "The purpose of the Prime Directive is to set the stage for a respectful and constructive retrospective. By embracing this mindset, we create an environment where everyone feels safe to share openly, learn together, and improve as a team.",
    prime_directive_statement: "'Regardless of what we discover, we understand and truly believe that everyone did the best job they could, given what they knew at the time, their skills and abilities, the resources available, and the situation at hand.'",
    user_guide_purpose: "The purpose of the retrospective is to build a practice of gathering feedback and continuously improving by acting on that feedback. The Retrospective extension and Team Assessment feature are valuable tools supporting that process.",
    user_guide_instructions: "For instructions on getting started, using the Retrospective extension and Team Assessment feature, and best practices for running effective retrospectives, open the user guide documented in the Readme file.",
    keyboard_shortcuts_instructions: "Use these keyboard shortcuts to navigate and interact with the retrospective board.",
    app_error_boundary_heading: "We detected an error in the application",
    app_init_failed_heading: "Unable to load Retrospectives",
    app_init_failed_description: "The extension failed to initialize. This can happen if browser extensions, tracking prevention, or security tools are blocking required resources.",
    app_init_failed_steps_heading: "Try these steps:",
    app_init_failed_step_incognito: "Open this page in an InPrivate or Incognito window",
    app_init_failed_step_disable_extensions: "Disable browser extensions temporarily",
    app_init_failed_step_tracking_prevention: "Check that tracking prevention is not set to Strict",
    app_init_failed_step_refresh: "Refresh the page",
    feedback_board_team_list_error: "We are unable to retrieve the list of teams for this project. Try reloading the page.",
    workflow_move_everyone: "Move everyone",
    workflow_move_everyone_to_phase: "Move everyone to {{phase}}",
    workflow_move_everyone_to_phase_success: "Everyone was moved to {{phase}}.",
    workflow_move_everyone_to_phase_error: "Could not move everyone to {{phase}}. Try again.",
    workflow_move_everyone_live_sync_unavailable: "Live sync is unavailable.",
    feedback_board_link_copied: "The link to retrospective {{title}} ({{phase}} phase) has been copied to your clipboard.",
    feedback_board_email_copied: "The email summary for \"{{title}}\" has been copied to your clipboard.",
    feedback_board_answer_all_questions: "Please answer all questions before saving",
    feedback_board_archive_title: "Archive retrospective",
    feedback_board_archive_message: "The retrospective board {{title}} with its feedback will be archived.",
    feedback_board_archive_note: "Archived retrospectives remain available on the History tab, where they can be restored or deleted.",
    feedback_board_archive_button: "Archive",
    feedback_board_create_new: "Create new retrospective",
    feedback_board_create_copy: "Create copy of retrospective",
    feedback_board_edit: "Edit retrospective settings",
    feedback_board_view_settings: "View retrospective settings",
    feedback_board_search_all_boards: "Search all boards",
    feedback_board_export_csv_content: "Export CSV content",
    feedback_board_create_example: "Example: {{date}} Retrospective",
    feedback_board_create_email_summary: "Create email summary",
    feedback_board_email_summary: "Email summary",
    feedback_board_email_summary_aria: "Email summary for retrospective",
    feedback_board_show_retro_summary: "Show retrospective summary",
    feedback_board_retro_summary: "Retrospective summary",
    feedback_board_basic_settings: "Basic Settings",
    feedback_board_created_date: "Created date: {{date}}",
    feedback_board_created_by: "Created by",
    feedback_board_participant_summary: "Participant Summary",
    feedback_board_contributors_count: "Contributors: {{count}} participant(s)",
    feedback_board_votes_summary: "{{participants}} participant(s) casted {{votes}} vote(s)",
    feedback_board_feedback_items_created: "{{count}} feedback item(s) created",
    feedback_board_action_items_created: "{{count}} action item(s) created",
    feedback_board_focus_mode: "Focus Mode",
    feedback_board_focus_mode_tooltip: "Focus Mode allows your team to focus on one feedback item at a time. Try it!",
    feedback_board_team_assessment_history: "Team Assessment History",
    feedback_board_team_assessment_no_history: "No team assessment history available.",
    feedback_board_team_assessment_trends: "Create retrospectives with team assessments to see historical trends.",
    feedback_board_team_assessment_showing_average_scores: "Showing average scores over time across {{count}} retrospective{{suffix}}.",
    feedback_board_team_assessment_history_chart_aria: "Team assessment history line chart showing scores over time",
    feedback_board_average_score: "Average Score",
    feedback_board_permissions: "Permissions",
    feedback_board_permission_settings: "Board Permission Settings",
    board_summary_work_item_type_icon: "Work item type icon",
    board_summary_work_item_icon: "Work Item Icon",
    board_summary_work_item_title: "Work item title",
    board_summary_icon_alt: "{{type}} icon",
    board_summary_title: "Title",
    board_summary_work_item_state: "Work item state",
    board_summary_state: "State",
    board_summary_work_item_type: "Work item type",
    board_summary_type: "Type",
    board_summary_work_item_changed_date: "Work item changed date",
    board_summary_last_updated: "Last Updated",
    board_summary_work_item_assigned_to: "Work item assigned to",
    board_summary_assigned_to: "Assigned To",
    board_summary_work_item_priority: "Work item priority",
    board_summary_priority: "Priority",
    board_summary_table_toggle_archive_enable_delete: "Toggle archive off and on to enable delete.",
    board_summary_table_delete_board: "Delete board",
    delete_retrospective_board: "Delete retrospective board",
    board_summary_table_wait_to_delete: "To delete this board, you must wait for 2 minutes after archiving.",
    board_summary_table_expand_row: "Expand Row",
    board_summary_table_retrospective_name: "Retrospective Name",
    board_summary_table_created_date: "Created Date",
    board_summary_table_archived: "Archived",
    board_summary_table_archived_date: "Archived Date",
    board_summary_table_feedback_items: "Feedback Items",
    board_summary_table_total_work_items: "Total Work Items",
    board_summary_table_delete_help: "Archived boards can be deleted by board owner or team admin.",
    sprint_retro_board_title: "{{iteration}} Retrospective",
    sprint_retro_create_current: "Create new for current sprint",
    sprint_retro_current_not_found: "No current sprint is configured for this team.",
  },
  es: {
    common_loading: "Cargando...",
    common_close: "Cerrar",
    common_save: "Guardar",
    common_cancel: "Cancelar",
    common_confirm: "Confirmar",
    common_reset: "Restablecer",
    common_remove: "Eliminar",
    common_delete: "Eliminar",
    common_link_work_item: "Vincular elemento de trabajo",
    common_link_existing_work_item: "Vincular elemento de trabajo existente",
    common_remove_link_to_work_item: "Quitar vinculo al elemento de trabajo",
    common_add_work_item_menu: "Menu para agregar elemento de trabajo",
    common_add_work_item: "Agregar elemento de trabajo",
    common_copy_to_clipboard: "Copiar al portapapeles",
    common_download_pdf: "Descargar PDF",
    common_description: "Descripcion",
    common_data: "Datos",
    common_help: "Ayuda",
    common_settings: "Configuracion",
    scroll_by_column: "Desplazarse por columna",
    scroll_by_board: "Desplazarse por tablero",
    show_all_teams: "Mostrar todos los equipos",
    show_my_teams: "Mostrar mis equipos",
    column_notes: "Notas de columna",
    edit_column_notes: "Editar notas de columna",
    add_new_feedback: "Agregar nuevo feedback",
    remove_feedback_from_group: "Quitar feedback del grupo",
    volunteer: "Voluntariado",
    the_prime_directive: "La Directiva Principal",
    open_retrospective_wiki: "Abrir la wiki de retrospectivas",
    open_user_guide: "Abrir guia de usuario",
    open_contributing_guidelines: "Abrir directrices de contribucion",
    prime_directive: "Directiva",
    data_import_export: "Importacion/exportacion de datos",
    import_data: "Importar datos",
    export_data: "Exportar datos",
    retrospective_help: "Ayuda de retrospectivas",
    retrospective_settings: "Configuracion de usuario/admin",
    whats_new: "Novedades",
    keyboard_shortcuts: "Atajos de teclado",
    contact_us: "Contactanos",
    user_guide: "Guia de usuario",
    prime_directive_purpose: "El proposito de la Directiva Principal es preparar el escenario para una retrospectiva respetuosa y constructiva. Al adoptar esta mentalidad, creamos un entorno donde todos se sienten seguros para compartir abiertamente, aprender juntos y mejorar como equipo.",
    prime_directive_statement: "'Independientemente de lo que descubramos, entendemos y creemos sinceramente que todos hicieron el mejor trabajo posible, teniendo en cuenta lo que sabian en ese momento, sus habilidades y capacidades, los recursos disponibles y la situacion en cuestion.'",
    user_guide_purpose: "El proposito de la retrospectiva es crear una practica de recopilar feedback y mejorar continuamente actuando sobre ese feedback. La extension Retrospective y la funcionalidad Team Assessment son herramientas valiosas que respaldan ese proceso.",
    user_guide_instructions: "Para obtener instrucciones sobre como comenzar, usar la extension Retrospective y la funcionalidad Team Assessment, y buenas practicas para realizar retrospectivas efectivas, abre la guia de usuario documentada en el archivo Readme.",
    keyboard_shortcuts_instructions: "Usa estos atajos de teclado para navegar e interactuar con el tablero de retrospectiva.",
    app_error_boundary_heading: "Detectamos un error en la aplicacion",
    app_init_failed_heading: "No se pudo cargar Retrospectives",
    app_init_failed_description: "La extension no pudo iniciarse. Esto puede ocurrir si extensiones del navegador, prevencion de rastreo o herramientas de seguridad estan bloqueando recursos necesarios.",
    app_init_failed_steps_heading: "Prueba estos pasos:",
    app_init_failed_step_incognito: "Abre esta pagina en una ventana InPrivate o Incognito",
    app_init_failed_step_disable_extensions: "Deshabilita temporalmente las extensiones del navegador",
    app_init_failed_step_tracking_prevention: "Comprueba que la prevencion de rastreo no este en modo estricto",
    app_init_failed_step_refresh: "Recarga la pagina",
    feedback_board_team_list_error: "No podemos recuperar la lista de equipos de este proyecto. Intenta recargar la pagina.",
    workflow_move_everyone: "Mover a todos",
    workflow_move_everyone_to_phase: "Mover a todos a {{phase}}",
    workflow_move_everyone_to_phase_success: "Todos fueron movidos a {{phase}}.",
    workflow_move_everyone_to_phase_error: "No se pudo mover a todos a {{phase}}. Intentalo de nuevo.",
    workflow_move_everyone_live_sync_unavailable: "La sincronizacion en vivo no esta disponible.",
    feedback_board_link_copied: "El enlace a la retrospectiva {{title}} (fase {{phase}}) se copio a tu portapapeles.",
    feedback_board_email_copied: "El resumen por correo de \"{{title}}\" se copio a tu portapapeles.",
    feedback_board_answer_all_questions: "Responde todas las preguntas antes de guardar",
    feedback_board_archive_title: "Archivar la retrospectiva",
    feedback_board_archive_message: "Se archivara el tablero de retrospectiva {{title}} con sus comentarios.",
    feedback_board_archive_note: "Las retrospectivas archivadas siguen disponibles en la pestana History, donde pueden restaurarse o eliminarse.",
    feedback_board_archive_button: "Archivar",
    feedback_board_create_new: "Crear nueva retrospectiva",
    feedback_board_create_copy: "Crear copia de la retrospectiva",
    feedback_board_edit: "Editar configuracion de la retrospectiva",
    feedback_board_view_settings: "Ver configuracion de la retrospectiva",
    feedback_board_search_all_boards: "Buscar en todos los tableros",
    feedback_board_export_csv_content: "Exportar contenido CSV",
    feedback_board_create_example: "Ejemplo: Retrospectiva {{date}}",
    feedback_board_create_email_summary: "Crear resumen por correo",
    feedback_board_email_summary: "Resumen por correo",
    feedback_board_email_summary_aria: "Resumen por correo de la retrospectiva",
    feedback_board_show_retro_summary: "Mostrar resumen de la retrospectiva",
    feedback_board_retro_summary: "Resumen del tablero de retrospectiva",
    feedback_board_basic_settings: "Configuracion basica",
    feedback_board_created_date: "Fecha de creacion: {{date}}",
    feedback_board_created_by: "Creado por",
    feedback_board_participant_summary: "Resumen de participantes",
    feedback_board_contributors_count: "Colaboradores: {{count}} participante(s)",
    feedback_board_votes_summary: "{{participants}} participante(s) emitieron {{votes}} voto(s)",
    feedback_board_feedback_items_created: "{{count}} elemento(s) de feedback creado(s)",
    feedback_board_action_items_created: "{{count}} accion(es) creada(s)",
    feedback_board_focus_mode: "Modo de enfoque",
    feedback_board_focus_mode_tooltip: "El modo de enfoque permite que tu equipo se centre en un elemento de feedback a la vez. Pruebalo!",
    feedback_board_team_assessment_history: "Historial de evaluacion del equipo",
    feedback_board_team_assessment_no_history: "No hay historial de evaluacion del equipo.",
    feedback_board_team_assessment_trends: "Crea retrospectivas con evaluaciones del equipo para ver tendencias historicas.",
    feedback_board_team_assessment_showing_average_scores: "Mostrando puntuaciones promedio en {{count}} retrospectiva{{suffix}}.",
    feedback_board_team_assessment_history_chart_aria: "Grafico de lineas del historial de evaluacion del equipo con puntuaciones a lo largo del tiempo",
    feedback_board_average_score: "Puntuacion promedio",
    feedback_board_permissions: "Permisos",
    feedback_board_permission_settings: "Configuracion de permisos del tablero",
    board_summary_work_item_type_icon: "Icono del tipo de elemento de trabajo",
    board_summary_work_item_icon: "Icono del elemento de trabajo",
    board_summary_work_item_title: "Titulo del elemento de trabajo",
    board_summary_icon_alt: "Icono de {{type}}",
    board_summary_title: "Titulo",
    board_summary_work_item_state: "Estado del elemento de trabajo",
    board_summary_state: "Estado",
    board_summary_work_item_type: "Tipo de elemento de trabajo",
    board_summary_type: "Tipo",
    board_summary_work_item_changed_date: "Fecha de actualizacion del elemento de trabajo",
    board_summary_last_updated: "Ultima actualizacion",
    board_summary_work_item_assigned_to: "Elemento de trabajo asignado a",
    board_summary_assigned_to: "Asignado a",
    board_summary_work_item_priority: "Prioridad del elemento de trabajo",
    board_summary_priority: "Prioridad",
    board_summary_table_toggle_archive_enable_delete: "Desactiva y vuelve a activar el archivo para habilitar la eliminacion.",
    board_summary_table_delete_board: "Eliminar tablero",
    delete_retrospective_board: "Eliminar tablero de retrospectiva",
    board_summary_table_wait_to_delete: "Para eliminar este tablero, debes esperar 2 minutos despues de archivarlo.",
    board_summary_table_expand_row: "Expandir fila",
    board_summary_table_retrospective_name: "Nombre de la retrospectiva",
    board_summary_table_created_date: "Fecha de creacion",
    board_summary_table_archived: "Archivado",
    board_summary_table_archived_date: "Fecha de archivo",
    board_summary_table_feedback_items: "Elementos de feedback",
    board_summary_table_total_work_items: "Elementos de trabajo totales",
    board_summary_table_delete_help: "Los tableros archivados pueden ser eliminados por el propietario o por un administrador del equipo.",
    sprint_retro_board_title: "{{iteration}} Retrospective",
    sprint_retro_create_current: "Create new for current sprint",
    sprint_retro_current_not_found: "No current sprint is configured for this team.",
  },
  de: {
    common_loading: "Wird geladen...",
    common_close: "Schliessen",
    common_save: "Speichern",
    common_cancel: "Abbrechen",
    common_confirm: "Bestaetigen",
    common_reset: "Zuruecksetzen",
    common_remove: "Entfernen",
    common_delete: "Loeschen",
    common_link_work_item: "Arbeitselement verknuepfen",
    common_link_existing_work_item: "Vorhandenes Arbeitselement verknuepfen",
    common_remove_link_to_work_item: "Verknuepfung zum Arbeitselement entfernen",
    common_add_work_item_menu: "Menue zum Hinzufuegen von Arbeitselementen",
    common_add_work_item: "Arbeitselement hinzufuegen",
    common_copy_to_clipboard: "In die Zwischenablage kopieren",
    common_download_pdf: "PDF herunterladen",
    common_description: "Beschreibung",
    common_data: "Daten",
    common_help: "Hilfe",
    common_settings: "Einstellungen",
    scroll_by_column: "Nach Spalte scrollen",
    scroll_by_board: "Nach Board scrollen",
    show_all_teams: "Alle Teams anzeigen",
    show_my_teams: "Meine Teams anzeigen",
    column_notes: "Spaltennotizen",
    edit_column_notes: "Spaltennotizen bearbeiten",
    add_new_feedback: "Neues Feedback hinzufuegen",
    remove_feedback_from_group: "Feedback aus der Gruppe entfernen",
    volunteer: "Mitwirken",
    the_prime_directive: "Die Prime Directive",
    open_retrospective_wiki: "Retrospektiven-Wiki oeffnen",
    open_user_guide: "Benutzerhandbuch oeffnen",
    open_contributing_guidelines: "Beitragsrichtlinien oeffnen",
    prime_directive: "Direktive",
    data_import_export: "Datenimport/-export",
    import_data: "Daten importieren",
    export_data: "Daten exportieren",
    retrospective_help: "Retrospektiven-Hilfe",
    retrospective_settings: "Benutzer-/Admin-Einstellungen",
    whats_new: "Neuigkeiten",
    keyboard_shortcuts: "Tastenkombinationen",
    contact_us: "Kontakt",
    user_guide: "Benutzerhandbuch",
    prime_directive_purpose: "Der Zweck der Prime Directive ist es, den Rahmen fuer eine respektvolle und konstruktive Retrospektive zu schaffen. Mit dieser Haltung schaffen wir eine Umgebung, in der sich alle sicher fuehlen, offen zu teilen, gemeinsam zu lernen und uns als Team zu verbessern.",
    prime_directive_statement: "'Unabhaengig davon, was wir entdecken, verstehen und glauben wir wirklich, dass jeder die bestmoegliche Arbeit geleistet hat, basierend auf dem, was er zu diesem Zeitpunkt wusste, seinen Faehigkeiten und Fertigkeiten, den verfuegbaren Ressourcen und der aktuellen Situation.'",
    user_guide_purpose: "Der Zweck der Retrospektive ist es, eine Praxis zu etablieren, Feedback zu sammeln und durch Handeln auf dieses Feedback kontinuierlich besser zu werden. Die Retrospective-Erweiterung und die Team Assessment-Funktion sind wertvolle Werkzeuge, die diesen Prozess unterstuetzen.",
    user_guide_instructions: "Anleitungen fuer den Einstieg, die Verwendung der Retrospective-Erweiterung und der Team Assessment-Funktion sowie Best Practices fuer effektive Retrospektiven finden Sie im Benutzerhandbuch in der Readme-Datei.",
    keyboard_shortcuts_instructions: "Verwenden Sie diese Tastenkombinationen, um im Retrospektiven-Board zu navigieren und damit zu interagieren.",
    app_error_boundary_heading: "Wir haben einen Fehler in der Anwendung erkannt",
    app_init_failed_heading: "Retrospectives konnte nicht geladen werden",
    app_init_failed_description: "Die Erweiterung konnte nicht initialisiert werden. Dies kann passieren, wenn Browsererweiterungen, Tracking-Schutz oder Sicherheitstools erforderliche Ressourcen blockieren.",
    app_init_failed_steps_heading: "Versuchen Sie diese Schritte:",
    app_init_failed_step_incognito: "Oeffnen Sie diese Seite in einem InPrivate- oder Inkognito-Fenster",
    app_init_failed_step_disable_extensions: "Deaktivieren Sie Browsererweiterungen voruebergehend",
    app_init_failed_step_tracking_prevention: "Pruefen Sie, dass der Tracking-Schutz nicht auf Streng gesetzt ist",
    app_init_failed_step_refresh: "Aktualisieren Sie die Seite",
    feedback_board_team_list_error: "Die Teamliste fuer dieses Projekt konnte nicht abgerufen werden. Versuchen Sie, die Seite neu zu laden.",
    workflow_move_everyone: "Alle verschieben",
    workflow_move_everyone_to_phase: "Alle zu {{phase}} verschieben",
    workflow_move_everyone_to_phase_success: "Alle wurden zu {{phase}} verschoben.",
    workflow_move_everyone_to_phase_error: "Alle konnten nicht zu {{phase}} verschoben werden. Versuchen Sie es erneut.",
    workflow_move_everyone_live_sync_unavailable: "Die Live-Synchronisierung ist nicht verfuegbar.",
    feedback_board_link_copied: "Der Link zur Retrospektive {{title}} (Phase {{phase}}) wurde in Ihre Zwischenablage kopiert.",
    feedback_board_email_copied: "Die E-Mail-Zusammenfassung fuer \"{{title}}\" wurde in Ihre Zwischenablage kopiert.",
    feedback_board_answer_all_questions: "Bitte beantworten Sie alle Fragen, bevor Sie speichern",
    feedback_board_archive_title: "Retrospektive archivieren",
    feedback_board_archive_message: "Das Retrospektiven-Board {{title}} wird zusammen mit seinem Feedback archiviert.",
    feedback_board_archive_note: "Archivierte Retrospektiven bleiben auf der Registerkarte History verfuegbar, wo sie wiederhergestellt oder geloescht werden koennen.",
    feedback_board_archive_button: "Archivieren",
    feedback_board_create_new: "Neue Retrospektive erstellen",
    feedback_board_create_copy: "Kopie der Retrospektive erstellen",
    feedback_board_edit: "Retrospektiveneinstellungen bearbeiten",
    feedback_board_view_settings: "Retrospektiveneinstellungen anzeigen",
    feedback_board_search_all_boards: "Alle Boards durchsuchen",
    feedback_board_export_csv_content: "CSV-Inhalt exportieren",
    feedback_board_create_example: "Beispiel: Retrospektive {{date}}",
    feedback_board_create_email_summary: "E-Mail-Zusammenfassung erstellen",
    feedback_board_email_summary: "E-Mail-Zusammenfassung",
    feedback_board_email_summary_aria: "E-Mail-Zusammenfassung fuer die Retrospektive",
    feedback_board_show_retro_summary: "Retrospektivenzusammenfassung anzeigen",
    feedback_board_retro_summary: "Zusammenfassung des Retrospektiven-Boards",
    feedback_board_basic_settings: "Grundeinstellungen",
    feedback_board_created_date: "Erstellt am: {{date}}",
    feedback_board_created_by: "Erstellt von",
    feedback_board_participant_summary: "Teilnehmerzusammenfassung",
    feedback_board_contributors_count: "Mitwirkende: {{count}} Teilnehmer",
    feedback_board_votes_summary: "{{participants}} Teilnehmer haben {{votes}} Stimmen abgegeben",
    feedback_board_feedback_items_created: "{{count}} Feedback-Eintraege erstellt",
    feedback_board_action_items_created: "{{count}} Aktionspunkte erstellt",
    feedback_board_focus_mode: "Fokusmodus",
    feedback_board_focus_mode_tooltip: "Im Fokusmodus kann sich Ihr Team jeweils auf einen Feedback-Eintrag konzentrieren. Probieren Sie ihn aus!",
    feedback_board_team_assessment_history: "Verlauf der Team-Bewertung",
    feedback_board_team_assessment_no_history: "Kein Verlauf der Team-Bewertung verfuegbar.",
    feedback_board_team_assessment_trends: "Erstellen Sie Retrospektiven mit Team-Bewertungen, um historische Trends zu sehen.",
    feedback_board_team_assessment_showing_average_scores: "Durchschnittswerte im Zeitverlauf ueber {{count}} Retrospektive{{suffix}} werden angezeigt.",
    feedback_board_team_assessment_history_chart_aria: "Liniendiagramm des Verlaufs der Team-Bewertung mit Werten im Zeitverlauf",
    feedback_board_average_score: "Durchschnittswert",
    feedback_board_permissions: "Berechtigungen",
    feedback_board_permission_settings: "Einstellungen fuer Board-Berechtigungen",
    board_summary_work_item_type_icon: "Symbol fuer Arbeitselementtyp",
    board_summary_work_item_icon: "Arbeitselementsymbol",
    board_summary_work_item_title: "Titel des Arbeitselements",
    board_summary_icon_alt: "{{type}}-Symbol",
    board_summary_title: "Titel",
    board_summary_work_item_state: "Status des Arbeitselements",
    board_summary_state: "Status",
    board_summary_work_item_type: "Typ des Arbeitselements",
    board_summary_type: "Typ",
    board_summary_work_item_changed_date: "Aenderungsdatum des Arbeitselements",
    board_summary_last_updated: "Zuletzt aktualisiert",
    board_summary_work_item_assigned_to: "Arbeitselement zugewiesen an",
    board_summary_assigned_to: "Zugewiesen an",
    board_summary_work_item_priority: "Prioritaet des Arbeitselements",
    board_summary_priority: "Prioritaet",
    board_summary_table_toggle_archive_enable_delete: "Deaktivieren und aktivieren Sie das Archiv erneut, um das Loeschen zu aktivieren.",
    board_summary_table_delete_board: "Board loeschen",
    delete_retrospective_board: "Retrospektiven-Board loeschen",
    board_summary_table_wait_to_delete: "Um dieses Board zu loeschen, muessen Sie nach dem Archivieren 2 Minuten warten.",
    board_summary_table_expand_row: "Zeile erweitern",
    board_summary_table_retrospective_name: "Name der Retrospektive",
    board_summary_table_created_date: "Erstellungsdatum",
    board_summary_table_archived: "Archiviert",
    board_summary_table_archived_date: "Archivierungsdatum",
    board_summary_table_feedback_items: "Feedback-Eintraege",
    board_summary_table_total_work_items: "Arbeitselemente gesamt",
    board_summary_table_delete_help: "Archivierte Boards koennen vom Board-Besitzer oder einem Team-Administrator geloescht werden.",
    sprint_retro_board_title: "{{iteration}} Retrospective",
    sprint_retro_create_current: "Create new for current sprint",
    sprint_retro_current_not_found: "No current sprint is configured for this team.",
  },
  fr: {
    common_loading: "Chargement...",
    common_close: "Fermer",
    common_save: "Enregistrer",
    common_cancel: "Annuler",
    common_confirm: "Confirmer",
    common_reset: "Reinitialiser",
    common_remove: "Supprimer",
    common_delete: "Supprimer",
    common_link_work_item: "Lier un element de travail",
    common_link_existing_work_item: "Lier un element de travail existant",
    common_remove_link_to_work_item: "Supprimer le lien vers l'element de travail",
    common_add_work_item_menu: "Menu Ajouter un element de travail",
    common_add_work_item: "Ajouter un element de travail",
    common_copy_to_clipboard: "Copier dans le presse-papiers",
    common_download_pdf: "Telecharger le PDF",
    common_description: "Description",
    common_data: "Donnees",
    common_help: "Aide",
    common_settings: "Parametres",
    scroll_by_column: "Faire defiler par colonne",
    scroll_by_board: "Faire defiler par tableau",
    show_all_teams: "Afficher toutes les equipes",
    show_my_teams: "Afficher mes equipes",
    column_notes: "Notes de colonne",
    edit_column_notes: "Modifier les notes de colonne",
    add_new_feedback: "Ajouter un nouveau feedback",
    remove_feedback_from_group: "Retirer le feedback du groupe",
    volunteer: "Contribuer",
    the_prime_directive: "La directive principale",
    open_retrospective_wiki: "Ouvrir le wiki des retrospectives",
    open_user_guide: "Ouvrir le guide utilisateur",
    open_contributing_guidelines: "Ouvrir les consignes de contribution",
    prime_directive: "Directive",
    data_import_export: "Import/export de donnees",
    import_data: "Importer les donnees",
    export_data: "Exporter les donnees",
    retrospective_help: "Aide sur les retrospectives",
    retrospective_settings: "Parametres utilisateur/admin",
    whats_new: "Nouveautes",
    keyboard_shortcuts: "Raccourcis clavier",
    contact_us: "Contactez-nous",
    user_guide: "Guide utilisateur",
    prime_directive_purpose: "Le but de la directive principale est de preparer une retrospective respectueuse et constructive. En adoptant cet etat d'esprit, nous creons un environnement ou chacun se sent en securite pour partager ouvertement, apprendre ensemble et progresser en equipe.",
    prime_directive_statement: "'Quel que soit ce que nous decouvrons, nous comprenons et croyons sincerement que chacun a fait le meilleur travail possible, compte tenu de ce qu'il savait a ce moment-la, de ses competences et capacites, des ressources disponibles et de la situation presente.'",
    user_guide_purpose: "Le but de la retrospective est d'etablir une pratique de collecte de feedback et d'amelioration continue en agissant sur ce feedback. L'extension Retrospective et la fonctionnalite Team Assessment sont des outils precieux qui soutiennent ce processus.",
    user_guide_instructions: "Pour obtenir des instructions sur le demarrage, l'utilisation de l'extension Retrospective et de la fonctionnalite Team Assessment, ainsi que les bonnes pratiques pour mener des retrospectives efficaces, ouvrez le guide utilisateur documente dans le fichier Readme.",
    keyboard_shortcuts_instructions: "Utilisez ces raccourcis clavier pour naviguer et interagir avec le tableau de retrospective.",
    app_error_boundary_heading: "Nous avons detecte une erreur dans l'application",
    app_init_failed_heading: "Impossible de charger Retrospectives",
    app_init_failed_description: "L'extension n'a pas pu etre initialisee. Cela peut se produire si des extensions du navigateur, la prevention du pistage ou des outils de securite bloquent des ressources necessaires.",
    app_init_failed_steps_heading: "Essayez les etapes suivantes :",
    app_init_failed_step_incognito: "Ouvrez cette page dans une fenetre InPrivate ou Incognito",
    app_init_failed_step_disable_extensions: "Desactivez temporairement les extensions du navigateur",
    app_init_failed_step_tracking_prevention: "Verifiez que la prevention du pistage n'est pas definie sur Strict",
    app_init_failed_step_refresh: "Actualisez la page",
    feedback_board_team_list_error: "Impossible de recuperer la liste des equipes pour ce projet. Essayez d'actualiser la page.",
    workflow_move_everyone: "Deplacer tout le monde",
    workflow_move_everyone_to_phase: "Deplacer tout le monde vers {{phase}}",
    workflow_move_everyone_to_phase_success: "Tout le monde a ete deplace vers {{phase}}.",
    workflow_move_everyone_to_phase_error: "Impossible de deplacer tout le monde vers {{phase}}. Reessayez.",
    workflow_move_everyone_live_sync_unavailable: "La synchronisation en direct n'est pas disponible.",
    feedback_board_link_copied: "Le lien vers la retrospective {{title}} (phase {{phase}}) a ete copie dans votre presse-papiers.",
    feedback_board_email_copied: "Le resume par e-mail de \"{{title}}\" a ete copie dans votre presse-papiers.",
    feedback_board_answer_all_questions: "Veuillez repondre a toutes les questions avant d'enregistrer",
    feedback_board_archive_title: "Archiver la retrospective",
    feedback_board_archive_message: "Le tableau de retrospective {{title}} sera archive avec ses commentaires.",
    feedback_board_archive_note: "Les retrospectives archivees restent disponibles dans l'onglet History, ou elles peuvent etre restaurees ou supprimees.",
    feedback_board_archive_button: "Archiver",
    feedback_board_create_new: "Creer une nouvelle retrospective",
    feedback_board_create_copy: "Creer une copie de la retrospective",
    feedback_board_edit: "Modifier les parametres de la retrospective",
    feedback_board_view_settings: "Afficher les parametres de la retrospective",
    feedback_board_search_all_boards: "Rechercher dans tous les tableaux",
    feedback_board_export_csv_content: "Exporter le contenu CSV",
    feedback_board_create_example: "Exemple : Retrospective {{date}}",
    feedback_board_create_email_summary: "Creer un resume par e-mail",
    feedback_board_email_summary: "Resume par e-mail",
    feedback_board_email_summary_aria: "Resume par e-mail de la retrospective",
    feedback_board_show_retro_summary: "Afficher le resume de la retrospective",
    feedback_board_retro_summary: "Resume du tableau de retrospective",
    feedback_board_basic_settings: "Parametres de base",
    feedback_board_created_date: "Date de creation : {{date}}",
    feedback_board_created_by: "Cree par",
    feedback_board_participant_summary: "Resume des participants",
    feedback_board_contributors_count: "Contributeurs : {{count}} participant(s)",
    feedback_board_votes_summary: "{{participants}} participant(s) ont exprime {{votes}} vote(s)",
    feedback_board_feedback_items_created: "{{count}} element(s) de feedback cree(s)",
    feedback_board_action_items_created: "{{count}} action(s) creee(s)",
    feedback_board_focus_mode: "Mode Focus",
    feedback_board_focus_mode_tooltip: "Le mode Focus permet a votre equipe de se concentrer sur un element de feedback a la fois. Essayez-le !",
    feedback_board_team_assessment_history: "Historique de l'evaluation d'equipe",
    feedback_board_team_assessment_no_history: "Aucun historique d'evaluation d'equipe disponible.",
    feedback_board_team_assessment_trends: "Creez des retrospectives avec des evaluations d'equipe pour voir les tendances historiques.",
    feedback_board_team_assessment_showing_average_scores: "Affichage des scores moyens au fil du temps sur {{count}} retrospective{{suffix}}.",
    feedback_board_team_assessment_history_chart_aria: "Graphique en courbes de l'historique de l'evaluation d'equipe montrant les scores au fil du temps",
    feedback_board_average_score: "Score moyen",
    feedback_board_permissions: "Autorisations",
    feedback_board_permission_settings: "Parametres des autorisations du tableau",
    board_summary_work_item_type_icon: "Icône du type d'element de travail",
    board_summary_work_item_icon: "Icône de l'element de travail",
    board_summary_work_item_title: "Titre de l'element de travail",
    board_summary_icon_alt: "Icône {{type}}",
    board_summary_title: "Titre",
    board_summary_work_item_state: "Etat de l'element de travail",
    board_summary_state: "Etat",
    board_summary_work_item_type: "Type d'element de travail",
    board_summary_type: "Type",
    board_summary_work_item_changed_date: "Date de modification de l'element de travail",
    board_summary_last_updated: "Derniere mise a jour",
    board_summary_work_item_assigned_to: "Element de travail assigne a",
    board_summary_assigned_to: "Assigne a",
    board_summary_work_item_priority: "Priorite de l'element de travail",
    board_summary_priority: "Priorite",
    board_summary_table_toggle_archive_enable_delete: "Desactivez puis reactivez l'archivage pour activer la suppression.",
    board_summary_table_delete_board: "Supprimer le tableau",
    delete_retrospective_board: "Supprimer le tableau de retrospective",
    board_summary_table_wait_to_delete: "Pour supprimer ce tableau, vous devez attendre 2 minutes apres l'archivage.",
    board_summary_table_expand_row: "Developper la ligne",
    board_summary_table_retrospective_name: "Nom de la retrospective",
    board_summary_table_created_date: "Date de creation",
    board_summary_table_archived: "Archive",
    board_summary_table_archived_date: "Date d'archivage",
    board_summary_table_feedback_items: "Elements de feedback",
    board_summary_table_total_work_items: "Total des elements de travail",
    board_summary_table_delete_help: "Les tableaux archives peuvent etre supprimes par le proprietaire du tableau ou un administrateur d'equipe.",
    sprint_retro_board_title: "{{iteration}} Retrospective",
    sprint_retro_create_current: "Create new for current sprint",
    sprint_retro_current_not_found: "No current sprint is configured for this team.",
  },
} as const;

type SupportedLanguage = keyof typeof translations;
type TranslationKey = keyof (typeof translations)["en"];
type InterpolationValues = Record<string, string | number>;

let activeLocale = DEFAULT_LOCALE;
let activeLanguage: SupportedLanguage = "en";

function normalizeLocale(locale?: string | null): string {
  const candidate = locale?.trim().replace(/_/g, "-") || DEFAULT_LOCALE;

  try {
    return Intl.getCanonicalLocales(candidate)[0] ?? DEFAULT_LOCALE;
  } catch {
    return DEFAULT_LOCALE;
  }
}

function detectPreferredLocale(): string {
  const documentLocale = typeof document !== "undefined" ? document.documentElement.lang : "";
  const browserLocale = typeof navigator !== "undefined" ? (navigator.languages?.[0] ?? navigator.language) : "";

  return documentLocale || browserLocale || DEFAULT_LOCALE;
}

function resolveLanguage(locale: string): SupportedLanguage {
  const language = locale.toLowerCase().split("-")[0] as SupportedLanguage;

  return language in translations ? language : "en";
}

function interpolate(template: string, values?: InterpolationValues): string {
  if (!values) {
    return template;
  }

  return template.replace(/\{\{(\w+)\}\}/g, (_, key: string) => {
    if (!(key in values)) {
      return `{{${key}}}`;
    }

    return String(values[key]);
  });
}

export function setLocale(locale?: string | null): string {
  activeLocale = normalizeLocale(locale);
  activeLanguage = resolveLanguage(activeLocale);

  if (typeof document !== "undefined") {
    document.documentElement.lang = activeLocale;
  }

  return activeLocale;
}

export function initializeLocale(locale?: string | null): string {
  return setLocale(locale || detectPreferredLocale());
}

export function getCurrentLocale(): string {
  return activeLocale;
}

export function t(key: TranslationKey, values?: InterpolationValues): string {
  const template = translations[activeLanguage][key] ?? translations.en[key];

  return interpolate(template, values);
}

export function formatDate(value: Date | string | number, options?: Intl.DateTimeFormatOptions): string {
  return new Intl.DateTimeFormat(activeLocale, options).format(new Date(value));
}

export function formatNumber(value: number, options?: Intl.NumberFormatOptions): string {
  return new Intl.NumberFormat(activeLocale, options).format(value);
}
