name: 'CI for Backend'

on:
  pull_request:
    branches:
      - main
      - dev
      - 'releases/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Backend - Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        name: Check out repository

      - uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: '10.0.203'

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: changes
        with:
          filters: |
            src:
              - 'src/backend/**'
              - 'src/backend.tests/**'

      - if: steps.changes.outputs.src == 'true'
        run: dotnet restore --locked-mode
        name: Restore
        working-directory: '.'

      - if: steps.changes.outputs.src == 'true'
        run: dotnet build src/backend/CollaborationStateService.csproj
        name: Build

      - if: steps.changes.outputs.src == 'true'
        run: dotnet test src/backend.tests/RetrospectiveExtension.Backend.Tests.csproj --logger "trx;LogFileName=test-results.trx"
        name: Test

      - if: success() || failure()
        name: Upload backend test report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dotnet-test-results
          path: src/backend.tests/TestResults/test-results.trx
