name: "Package for Production"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to use"
        required: false

jobs:
  ci_cd_frontend:
    name: "Run frontend CI/CD"
    permissions:
      contents: read
      issues: read
      pull-requests: read
      statuses: write
      checks: write
    uses: ./.github/workflows/ci_cd_frontend.yml
    secrets: inherit

  package:
    needs: ci_cd_frontend
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Package extension
        id: package_extension
        working-directory: 'src/frontend'
        env:
          AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          REACT_APP_COLLABORATION_STATE_SERVICE_URL: ${{ secrets.BACKEND_WEBAPP }}
          REACT_APP_APP_INSIGHTS_INSTRUMENTATION_KEY: ${{ secrets.AI_INSTRUMENTATION_KEY }}
          INPUT_VERSION: ${{ inputs.version }}
        run: |
          npm ci

          if [ -z "${INPUT_VERSION}" ]; then
            ext_info=$(npx tfx extension show --no-prompt --json --publisher "ms-devlabs" --extensionId "team-retrospectives" --token "${AZURE_DEVOPS_TOKEN}")
            VERSION=$(jq -r '.versions[0].version' <<< "$ext_info")
          else
            VERSION="${INPUT_VERSION}"
          fi

          tmp_versioned=$(mktemp)
          jq ".version = \"${VERSION}\"" vss-extension-prod.json > "$tmp_versioned"
          mv "$tmp_versioned" vss-extension-prod.json

          cp ../../LICENSE ./assets/LICENSE.md

          npm run pack:p

          VERSION=$(jq -r '.version' vss-extension-prod.json)
          echo "extension_version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: "Upload extension package"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: retrospectives-extension-prod
          path: src/frontend/dist/*.vsix
          if-no-files-found: error

      - name: Create the tag for the extension release
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{ github.token }}
          script: |
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/v${{ steps.package_extension.outputs.extension_version }}`,
              sha: context.sha
            });
